name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
env:
  OMP_NUM_THREADS: '10'
  MKL_THREADING_LAYER: GNU
jobs:
  AMX-DNNL-cmake:
    name: AMX DNNL (cmake)
    runs-on: faiss-aws-m7i.large
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build_cmake
        with:
          dnnl: ON
